#!/usr/bin/python3


def fibbanccithing():
    """
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

        https://projecteuler.net/problem=2
    """
    maxamt = 4000000
    total = 0
    last = [0,1]
    evenlist = []
    while total < maxamt:
        total = last[-2] + last[-1]
        last.append(total)
    for i in last[2:]:
        if i % 2 == 0:
            evenlist.append(i)
    newtot = 0
    for i in evenlist:
        newtot = newtot + i
    print(newtot)  

fibbanccithing()
